### ISSUE TITLE
pass plugin-specific options to streamlink

### ISSUE THREAD

**Issue by mario-tux** [vstavrinov/streamlink-service#1]
Hi, 
I'm trying to use your service to stream BBC channels but streamlink requires credentials to make it work. I was not able to figure out how to pass the specific options by means of streamlink-service. 

This is the URL I used: `http://SERVER:PORT/?https://www.bbc.co.uk/iplayer/live/bbctwo+best&bbciplayer-username=USERNAME&bbciplayer-password=PASSWORD`
In this case streamlink continues to ask for them:
```
BBC iPlayer requires an account you must login using --bbciplayer-username and --bbciplayer-password
[pid: 11|app: 0|req: 12/24] 192.168.200.100 () {28 vars in 569 bytes} [Sat Jul 17 14:49:52 2021] GET /?https://www.bbc.co.uk/iplayer/live/bbctwo+best&bbciplayer-username=USERNAME@gmail.com&bbciplayer-password=PASSWORD => generated 27 bytes in 220 msecs (HTTP/1.1 200) 2 headers in 65 bytes (1 switches on core 1)
```

**Comment by mario-tux** [comment]
Looking at your code and at the plugin one I figured out that I should use something like: `http://SERVER:PORT/?https://www.bbc.co.uk/iplayer/live/bbctwo+best&username=USERNAME&password=PASSWORD`

**Comment by vstavrinov** [comment]
As stated in README: 

> Trailing '=' sign is necessary in this case because it is a shortcut for 'url=youtube.com/user/Bloomberg+best

So You have two options:

1. either best=
2. or url=
