### ISSUE TITLE
Problem playing a specific link

### ISSUE THREAD

**Issue by SoSJames** [vstavrinov/streamlink-service#2]
Hi,

I'm trying to use your streamlink service to play an HLS Variant playlist. In the ordinary version of streamlink, the link only works when enclosed in quotes. I attempted to replicate that with the url= parameter but playback fails.  The link looks like:

https://xxx.xxx.xxx/hls/live/2096103/2754047_3049813/master-archive.m3u8?cid=36306&mid=34544119&ecid=3049813&pid=5&dtid=1&ident=708031760372&hdnea=exp=1679003928~acl=*/hls/live/2096103/2754047_3049813/*~hmac=13962222d7dad91b86e7341a89048c99597b4e0272622681c7dffa4e6b051278&startTime=1678932020&endTime=1678946400&partnerid=1&apiProvider=LCO&content=1573653

Any suggestions?

**Comment by vstavrinov** [comment]
Give me exact link I will try to reproduce Your problem.

**Comment by SoSJames** [comment]
Here's the link:

https://spottnhl.akamaized.net/hls/live/2096108/2757127_3053187/master-archive.m3u8?cid=36306&mid=34544125&ecid=3053187&pid=5&dtid=1&ident=208637696524&hdnea=exp=1679061795~acl=*/hls/live/2096108/2757127_3053187/*~hmac=eeca4d9455fb3425fa59574a12afefc20f17c46093404618cd78828b87fc2437&startTime=1679007620&endTime=1679017067&partnerid=1&apiProvider=LCO&content=1574237

It's georestricted, however.  It should work in the UK, Japan, Ireland, Scotland and a few others. Basically outside of the US and Canada.

I'm also not sure if the link expires. Let me know if there's anything else you need, and I appreciate your help.

**Comment by vstavrinov** [comment]
Yes, I couldn't test this url possible because of geo restrictions, so try url encode i.e. replace question mark with %3F and ampersand with %26

**Comment by SoSJames** [comment]
I gave that a try, however, it looks like the link I was testing expired, since I can't play it directly anymore either. I should be able to try a different example later on this evening. Am I correct in assuming that I can use curl to see the streamlink output (so I might see an error if there is one)?

**Comment by SoSJames** [comment]
Just to follow up, I was able to grab an updated link, replace all instances of ampersands with %26 and manually specify a quality, and the link plays. I can set up a script to do this programmatically, so my issue is solved! many thanks for this excellent project and you're quick responses.

**Comment by vstavrinov** [comment]
@SoSJames wrote:
>  Am I correct in assuming that I can use curl to see the streamlink output (so I might see an error if there is one)?

Yes, You are right, You can use curl for debugging. But remember You can get binary stream in output. To avoid this use stream URL without stream identifier, e.g. remove +best= suffix.  This way You will get stream list in case OK and error output otherwise. Here is example:

`curl http://localhost:8080?nbcnews.com/now`

Available streams: ['144p_alt', '144p', '216p_alt', '216p', '288p_alt', '288p', '360p_alt', '360p', '504p_alt', '504p', '576p_alt', '576p', '720p_alt', '720p', '1080p_alt', '1080p', 'worst', 'best']

`curl http://localhost:8080?nbcnews.com/no`

Exception NoPluginError:
