### ISSUE TITLE
how to play youtube video link

### ISSUE THREAD

**Issue by muziling** [vstavrinov/streamlink-service#3]
for example link : https://www.youtube.com/watch?v=7RqTPxcZB7Q
or link: https://www.youtube.com/watch?v=gN0PZCe-kwQ

replace `user/Bloomberg+best=` in link: `http://localhost:8000/?youtube.com/user/Bloomberg=`  to what ?

**Comment by muziling** [comment]
I create a pull request

**Comment by vstavrinov** [comment]
This case described in the README, the quote: 

"If the URL itself contains query string then url should be set in key/value style like others, i.e. url=" 

I.e. in this case, You must use url parameter explicitly. The equal sign "=" at the end is just shortcut for this parameter. URL, provided by You works for me this way:

```mpv http://localhost:8080?url=youtube.com/watch?v=gN0PZCe-kwQ+best```
